name: PHP Composer

on:
  push:
    branches: [ main, actions/add-workflow ]
  pull_request:
    branches: [ main, actions/add-workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GitHub Action for PHPUnit
      # You may pin to the exact commit or the version.
      # uses: owenvoke/phpunit-action@41a9b79e02fea917da3974de5272dd7ceac425b8
      uses: owenvoke/phpunit-action@v1.0.0
      with:
        # User defined command
        command: phpunit wp-content/plugins/wc-invoice-payment-gateway/tests
